config/routes.rb
Sknaacp1166::Application.routes.draw do
  devise_for :users
  get 'home/', to: 'pages#index'
  post '/send_message', to: 'pages#send_message'
  resources :posts
  root 'pages#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def send_message
    @message = {}
    @message[:name] = params[:name]
    @message[:email] = params[:email]
    @message[:message] = params[:message]
    Contact.send_contact_form(@message).deliver
    redirect_to '/', notice: "Your message has been sent"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :published_at, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contact/send_contact_form.html.erb
<html>
<body>
  Name: <%= @message[:name] %> <br /><br />
  Email: <%= @message[:email] %> <br /><br />
  <%= @message[:message] %>
</body>
</html>

app/views/layouts/application.html.slim
doctype html
html 
  head 
    title Salem-Keizer NAACP Branch 1166
    meta name="viewport" content="width=device-width initial-scale=1.0"
    == stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    == javascript_include_tag "application", "data-turbolinks-track" => true 
    == javascript_include_tag "http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"
    == javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/1.4.6/jquery.scrollTo.min.js"
    == javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"
    == javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"
    == csrf_meta_tags
  body#home
    .navbar.navbar-fixed-top role="navigation"
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed data-toggle="collapse" data-target=".navbar-collapse"
            i.icon-reorder.white 
          a.navbar-brand href="#" Salem-Keizer NAACP
        .navbar-collapse.collapse.navbar-right
          ul.nav.navbar-nav 
            li 
              == link_to  "Home", '#splash', class: "scroll"
            li 
              == link_to  "Calendar", '#calendar', class: "scroll"
            li 
              == link_to 'Join', '#join', class: "scroll"
            li 
              == link_to 'Contact', '#contact', class: "scroll"

    == yield

    footer
      .container-fluid
        .row
          .col-sm-12
            p 
              | &copy; 
              == Time.now.year 
              |  Salem-Keizer NAACP 1166

app/views/pages/index.html.slim
section#splash
  .container-fluid
    .row
      .col-sm-12
        == image_tag 'naacp_logo.png', class: "logo-image"
        h2.logo-text 
          | Salem-Keizer
          span.large NAACP 
          | Branch #1166
section#latest
  .container-fluid
    .row
      a.col-sm-12.col-md-8.card.white.medium href="youthflyer.pdf"
        span.title General Meeting May 5
        span.iconic.hidden-xs
          i.icon-calendar-empty.icon-4x.hidden-xs
      a.col-sm-12.col-md-3.col-md-offset-1.card.yellow.medium.scroll.center href="#join"
        span.title Join Branch 1166
section.interlude
  .container-fluid
    .row
      .col-sm-12
        p The vision of the National Association for the Advancement of Colored People is to ensure a society in which all individuals have equal rights without discrimination based on race.

section#calendar
  .container-fluid
    .row
      h2 Calendar
      .col-sm-12.col-md-8.card.blue.auto-height
        h2.title 
          | Branch 1166 General Meeting  
          small at 
          span.yellow Chemeketa Community College Multi-cultural Room
        p.yellow 
          | May 5, 2014 at 6:00 PM 
          
section#join
  .container-fluid
    .row
      .col-sm-12
        h2 Join NAACP Branch 1166
      .col-sm-7
        p Founded Feb. 12. 1909, the NAACP is the nation's oldest, largest and most widely recognized grassroots-based civil rights organization. Its more than half-million members and supporters throughout the United States and the world are the premier advocates for civil rights in their communities, campaigning for equal opportunity and conducting voter mobilization.
        p The Salem-Keizer branch of the NAACP was reformed in 1994 with over 200 memember. The goals of the Salem-Keizer NAACP include:
        ul
          li Responding Effectively to issues of discrimination in Salem and Keizer.
          li Providing opportunities for communal sharing and support amongst people of color in Salem-Keizer and;
          li Promoting a strong sense of inclusiveness and cooperation througout the Salem-Keizer community.
      .col-sm-4.col-md-3.col-md-offset-1
        h3 Join Today
        a.nbtn href="https://squareup.com/market/salem-keizer-naacp" Join the NAACP

section.interlude
  .container-fluid
    .row
      p The vision of the National Association for the Advancement of Colored People is to ensure a society in which all individuals have equal rights without discrimination based on race.

section#contact
  .container-fluid
    .row
      .col-sm-12
        h2 Contact
      
      == form_tag "/send_message", method: "post", id: "contact-form", class: "col-sm-12 col-md-6" do
        .success
          h3 Thank you. Your message was sent
          p We will be in contact with you as soon as possible.
        .form-group
          label for="name" Name
          == text_field '', 'name', class: 'form-control', required: 'true'
        .form-group
          label for="email" Email
          == email_field '', 'email', class: 'form-control', placeholder: 'yourname@domain.com', required: true, email: true
        .form-group
          label for="message" Message
          == text_area '', :message, rows: '10', class: 'form-control', required: true
        .form-group
          input.nbtn type="reset" value="Reset" 
          == submit_tag 'Submit', class: 'nbtn'
      .col-sm-4.col-sm-offset-2
        h4 Phone
        h4 Address
        address 
          | PO Box 13068
          br
          | Salem, OR 97309

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <h1>News</h1>
  <% @posts.each do |post| %>
    <h2><%= link_to post.title, post_path(post)%></h2>
    <p>Published: <%= post.published_at.strftime("%B %d, %Y") %></p>
    <%= post.body.truncate(300).html_safe %>
    <p>
     <% if current_user %>
      <%= link_to 'Edit', edit_post_path(post) %>
     <% end %>
    </p>
  <% end %>
</div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="alert info" id="notice"><%= notice %></div>
<div class="container">
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <h2><%= @post.title %></h2>
  <%= @post.body.html_safe %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>
</div>